// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: card.proto

#include "card.pb.h"
#include "card.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace card_reader_crt {

static const char* CardReader_method_names[] = {
  "/card_reader_crt.CardReader/IsOpen",
  "/card_reader_crt.CardReader/Open",
  "/card_reader_crt.CardReader/Close",
  "/card_reader_crt.CardReader/Init",
  "/card_reader_crt.CardReader/PermitMagCardOnly",
  "/card_reader_crt.CardReader/ProhibitCardIn",
  "/card_reader_crt.CardReader/Eject",
  "/card_reader_crt.CardReader/Capture",
  "/card_reader_crt.CardReader/Retrieve",
  "/card_reader_crt.CardReader/CardStatus",
  "/card_reader_crt.CardReader/LEDBlinkGreen",
  "/card_reader_crt.CardReader/LEDBlinkOrange",
  "/card_reader_crt.CardReader/LEDBlinkRed",
  "/card_reader_crt.CardReader/LEDOFF",
  "/card_reader_crt.CardReader/ReadData",
  "/card_reader_crt.CardReader/WaitInputReadCard",
  "/card_reader_crt.CardReader/RejectCardOrMoveBin",
  "/card_reader_crt.CardReader/GetDataKartu",
};

std::unique_ptr< CardReader::Stub> CardReader::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CardReader::Stub> stub(new CardReader::Stub(channel, options));
  return stub;
}

CardReader::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_IsOpen_(CardReader_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Open_(CardReader_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Close_(CardReader_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Init_(CardReader_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PermitMagCardOnly_(CardReader_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ProhibitCardIn_(CardReader_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Eject_(CardReader_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Capture_(CardReader_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Retrieve_(CardReader_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CardStatus_(CardReader_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LEDBlinkGreen_(CardReader_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LEDBlinkOrange_(CardReader_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LEDBlinkRed_(CardReader_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LEDOFF_(CardReader_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReadData_(CardReader_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_WaitInputReadCard_(CardReader_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RejectCardOrMoveBin_(CardReader_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDataKartu_(CardReader_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CardReader::Stub::IsOpen(::grpc::ClientContext* context, const ::card_reader_crt::IsOpenRequest& request, ::card_reader_crt::IsOpenResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::IsOpenRequest, ::card_reader_crt::IsOpenResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_IsOpen_, context, request, response);
}

void CardReader::Stub::async::IsOpen(::grpc::ClientContext* context, const ::card_reader_crt::IsOpenRequest* request, ::card_reader_crt::IsOpenResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::IsOpenRequest, ::card_reader_crt::IsOpenResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IsOpen_, context, request, response, std::move(f));
}

void CardReader::Stub::async::IsOpen(::grpc::ClientContext* context, const ::card_reader_crt::IsOpenRequest* request, ::card_reader_crt::IsOpenResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IsOpen_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::IsOpenResp>* CardReader::Stub::PrepareAsyncIsOpenRaw(::grpc::ClientContext* context, const ::card_reader_crt::IsOpenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::IsOpenResp, ::card_reader_crt::IsOpenRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_IsOpen_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::IsOpenResp>* CardReader::Stub::AsyncIsOpenRaw(::grpc::ClientContext* context, const ::card_reader_crt::IsOpenRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncIsOpenRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::Open(::grpc::ClientContext* context, const ::card_reader_crt::OpenRequest& request, ::card_reader_crt::OpenResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::OpenRequest, ::card_reader_crt::OpenResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Open_, context, request, response);
}

void CardReader::Stub::async::Open(::grpc::ClientContext* context, const ::card_reader_crt::OpenRequest* request, ::card_reader_crt::OpenResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::OpenRequest, ::card_reader_crt::OpenResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Open_, context, request, response, std::move(f));
}

void CardReader::Stub::async::Open(::grpc::ClientContext* context, const ::card_reader_crt::OpenRequest* request, ::card_reader_crt::OpenResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Open_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::OpenResp>* CardReader::Stub::PrepareAsyncOpenRaw(::grpc::ClientContext* context, const ::card_reader_crt::OpenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::OpenResp, ::card_reader_crt::OpenRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Open_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::OpenResp>* CardReader::Stub::AsyncOpenRaw(::grpc::ClientContext* context, const ::card_reader_crt::OpenRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncOpenRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::Close(::grpc::ClientContext* context, const ::card_reader_crt::CloseRequest& request, ::card_reader_crt::CloseResp* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::CloseRequest, ::card_reader_crt::CloseResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Close_, context, request, response);
}

void CardReader::Stub::async::Close(::grpc::ClientContext* context, const ::card_reader_crt::CloseRequest* request, ::card_reader_crt::CloseResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::CloseRequest, ::card_reader_crt::CloseResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Close_, context, request, response, std::move(f));
}

void CardReader::Stub::async::Close(::grpc::ClientContext* context, const ::card_reader_crt::CloseRequest* request, ::card_reader_crt::CloseResp* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Close_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::CloseResp>* CardReader::Stub::PrepareAsyncCloseRaw(::grpc::ClientContext* context, const ::card_reader_crt::CloseRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::CloseResp, ::card_reader_crt::CloseRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Close_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::CloseResp>* CardReader::Stub::AsyncCloseRaw(::grpc::ClientContext* context, const ::card_reader_crt::CloseRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCloseRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::Init(::grpc::ClientContext* context, const ::card_reader_crt::InitRequest& request, ::card_reader_crt::InitResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::InitRequest, ::card_reader_crt::InitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Init_, context, request, response);
}

void CardReader::Stub::async::Init(::grpc::ClientContext* context, const ::card_reader_crt::InitRequest* request, ::card_reader_crt::InitResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::InitRequest, ::card_reader_crt::InitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Init_, context, request, response, std::move(f));
}

void CardReader::Stub::async::Init(::grpc::ClientContext* context, const ::card_reader_crt::InitRequest* request, ::card_reader_crt::InitResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Init_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::InitResponse>* CardReader::Stub::PrepareAsyncInitRaw(::grpc::ClientContext* context, const ::card_reader_crt::InitRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::InitResponse, ::card_reader_crt::InitRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Init_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::InitResponse>* CardReader::Stub::AsyncInitRaw(::grpc::ClientContext* context, const ::card_reader_crt::InitRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncInitRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::PermitMagCardOnly(::grpc::ClientContext* context, const ::card_reader_crt::PermitMagCardOnlyRequest& request, ::card_reader_crt::PermitMagCardOnlyResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::PermitMagCardOnlyRequest, ::card_reader_crt::PermitMagCardOnlyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PermitMagCardOnly_, context, request, response);
}

void CardReader::Stub::async::PermitMagCardOnly(::grpc::ClientContext* context, const ::card_reader_crt::PermitMagCardOnlyRequest* request, ::card_reader_crt::PermitMagCardOnlyResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::PermitMagCardOnlyRequest, ::card_reader_crt::PermitMagCardOnlyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PermitMagCardOnly_, context, request, response, std::move(f));
}

void CardReader::Stub::async::PermitMagCardOnly(::grpc::ClientContext* context, const ::card_reader_crt::PermitMagCardOnlyRequest* request, ::card_reader_crt::PermitMagCardOnlyResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PermitMagCardOnly_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::PermitMagCardOnlyResponse>* CardReader::Stub::PrepareAsyncPermitMagCardOnlyRaw(::grpc::ClientContext* context, const ::card_reader_crt::PermitMagCardOnlyRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::PermitMagCardOnlyResponse, ::card_reader_crt::PermitMagCardOnlyRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PermitMagCardOnly_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::PermitMagCardOnlyResponse>* CardReader::Stub::AsyncPermitMagCardOnlyRaw(::grpc::ClientContext* context, const ::card_reader_crt::PermitMagCardOnlyRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPermitMagCardOnlyRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::ProhibitCardIn(::grpc::ClientContext* context, const ::card_reader_crt::ProhibitCardInRequest& request, ::card_reader_crt::ProhibitCardInResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::ProhibitCardInRequest, ::card_reader_crt::ProhibitCardInResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ProhibitCardIn_, context, request, response);
}

void CardReader::Stub::async::ProhibitCardIn(::grpc::ClientContext* context, const ::card_reader_crt::ProhibitCardInRequest* request, ::card_reader_crt::ProhibitCardInResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::ProhibitCardInRequest, ::card_reader_crt::ProhibitCardInResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProhibitCardIn_, context, request, response, std::move(f));
}

void CardReader::Stub::async::ProhibitCardIn(::grpc::ClientContext* context, const ::card_reader_crt::ProhibitCardInRequest* request, ::card_reader_crt::ProhibitCardInResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ProhibitCardIn_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::ProhibitCardInResponse>* CardReader::Stub::PrepareAsyncProhibitCardInRaw(::grpc::ClientContext* context, const ::card_reader_crt::ProhibitCardInRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::ProhibitCardInResponse, ::card_reader_crt::ProhibitCardInRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ProhibitCardIn_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::ProhibitCardInResponse>* CardReader::Stub::AsyncProhibitCardInRaw(::grpc::ClientContext* context, const ::card_reader_crt::ProhibitCardInRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProhibitCardInRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::Eject(::grpc::ClientContext* context, const ::card_reader_crt::EjectRequest& request, ::card_reader_crt::EjectResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::EjectRequest, ::card_reader_crt::EjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Eject_, context, request, response);
}

void CardReader::Stub::async::Eject(::grpc::ClientContext* context, const ::card_reader_crt::EjectRequest* request, ::card_reader_crt::EjectResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::EjectRequest, ::card_reader_crt::EjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Eject_, context, request, response, std::move(f));
}

void CardReader::Stub::async::Eject(::grpc::ClientContext* context, const ::card_reader_crt::EjectRequest* request, ::card_reader_crt::EjectResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Eject_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::EjectResponse>* CardReader::Stub::PrepareAsyncEjectRaw(::grpc::ClientContext* context, const ::card_reader_crt::EjectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::EjectResponse, ::card_reader_crt::EjectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Eject_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::EjectResponse>* CardReader::Stub::AsyncEjectRaw(::grpc::ClientContext* context, const ::card_reader_crt::EjectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncEjectRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::Capture(::grpc::ClientContext* context, const ::card_reader_crt::CaptureRequest& request, ::card_reader_crt::CaptureResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::CaptureRequest, ::card_reader_crt::CaptureResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Capture_, context, request, response);
}

void CardReader::Stub::async::Capture(::grpc::ClientContext* context, const ::card_reader_crt::CaptureRequest* request, ::card_reader_crt::CaptureResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::CaptureRequest, ::card_reader_crt::CaptureResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Capture_, context, request, response, std::move(f));
}

void CardReader::Stub::async::Capture(::grpc::ClientContext* context, const ::card_reader_crt::CaptureRequest* request, ::card_reader_crt::CaptureResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Capture_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::CaptureResponse>* CardReader::Stub::PrepareAsyncCaptureRaw(::grpc::ClientContext* context, const ::card_reader_crt::CaptureRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::CaptureResponse, ::card_reader_crt::CaptureRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Capture_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::CaptureResponse>* CardReader::Stub::AsyncCaptureRaw(::grpc::ClientContext* context, const ::card_reader_crt::CaptureRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCaptureRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::Retrieve(::grpc::ClientContext* context, const ::card_reader_crt::RetrieveRequest& request, ::card_reader_crt::RetrieveResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::RetrieveRequest, ::card_reader_crt::RetrieveResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Retrieve_, context, request, response);
}

void CardReader::Stub::async::Retrieve(::grpc::ClientContext* context, const ::card_reader_crt::RetrieveRequest* request, ::card_reader_crt::RetrieveResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::RetrieveRequest, ::card_reader_crt::RetrieveResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Retrieve_, context, request, response, std::move(f));
}

void CardReader::Stub::async::Retrieve(::grpc::ClientContext* context, const ::card_reader_crt::RetrieveRequest* request, ::card_reader_crt::RetrieveResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Retrieve_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::RetrieveResponse>* CardReader::Stub::PrepareAsyncRetrieveRaw(::grpc::ClientContext* context, const ::card_reader_crt::RetrieveRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::RetrieveResponse, ::card_reader_crt::RetrieveRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Retrieve_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::RetrieveResponse>* CardReader::Stub::AsyncRetrieveRaw(::grpc::ClientContext* context, const ::card_reader_crt::RetrieveRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRetrieveRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::CardStatus(::grpc::ClientContext* context, const ::card_reader_crt::CardStatusRequest& request, ::card_reader_crt::CardStatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::CardStatusRequest, ::card_reader_crt::CardStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CardStatus_, context, request, response);
}

void CardReader::Stub::async::CardStatus(::grpc::ClientContext* context, const ::card_reader_crt::CardStatusRequest* request, ::card_reader_crt::CardStatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::CardStatusRequest, ::card_reader_crt::CardStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CardStatus_, context, request, response, std::move(f));
}

void CardReader::Stub::async::CardStatus(::grpc::ClientContext* context, const ::card_reader_crt::CardStatusRequest* request, ::card_reader_crt::CardStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CardStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::CardStatusResponse>* CardReader::Stub::PrepareAsyncCardStatusRaw(::grpc::ClientContext* context, const ::card_reader_crt::CardStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::CardStatusResponse, ::card_reader_crt::CardStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CardStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::CardStatusResponse>* CardReader::Stub::AsyncCardStatusRaw(::grpc::ClientContext* context, const ::card_reader_crt::CardStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCardStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::LEDBlinkGreen(::grpc::ClientContext* context, const ::card_reader_crt::LEDBlinkGreenRequest& request, ::card_reader_crt::LEDBlinkGreenResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::LEDBlinkGreenRequest, ::card_reader_crt::LEDBlinkGreenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LEDBlinkGreen_, context, request, response);
}

void CardReader::Stub::async::LEDBlinkGreen(::grpc::ClientContext* context, const ::card_reader_crt::LEDBlinkGreenRequest* request, ::card_reader_crt::LEDBlinkGreenResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::LEDBlinkGreenRequest, ::card_reader_crt::LEDBlinkGreenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LEDBlinkGreen_, context, request, response, std::move(f));
}

void CardReader::Stub::async::LEDBlinkGreen(::grpc::ClientContext* context, const ::card_reader_crt::LEDBlinkGreenRequest* request, ::card_reader_crt::LEDBlinkGreenResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LEDBlinkGreen_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::LEDBlinkGreenResponse>* CardReader::Stub::PrepareAsyncLEDBlinkGreenRaw(::grpc::ClientContext* context, const ::card_reader_crt::LEDBlinkGreenRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::LEDBlinkGreenResponse, ::card_reader_crt::LEDBlinkGreenRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LEDBlinkGreen_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::LEDBlinkGreenResponse>* CardReader::Stub::AsyncLEDBlinkGreenRaw(::grpc::ClientContext* context, const ::card_reader_crt::LEDBlinkGreenRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLEDBlinkGreenRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::LEDBlinkOrange(::grpc::ClientContext* context, const ::card_reader_crt::LEDBlinkOrangeRequest& request, ::card_reader_crt::LEDBlinkOrangeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::LEDBlinkOrangeRequest, ::card_reader_crt::LEDBlinkOrangeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LEDBlinkOrange_, context, request, response);
}

void CardReader::Stub::async::LEDBlinkOrange(::grpc::ClientContext* context, const ::card_reader_crt::LEDBlinkOrangeRequest* request, ::card_reader_crt::LEDBlinkOrangeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::LEDBlinkOrangeRequest, ::card_reader_crt::LEDBlinkOrangeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LEDBlinkOrange_, context, request, response, std::move(f));
}

void CardReader::Stub::async::LEDBlinkOrange(::grpc::ClientContext* context, const ::card_reader_crt::LEDBlinkOrangeRequest* request, ::card_reader_crt::LEDBlinkOrangeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LEDBlinkOrange_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::LEDBlinkOrangeResponse>* CardReader::Stub::PrepareAsyncLEDBlinkOrangeRaw(::grpc::ClientContext* context, const ::card_reader_crt::LEDBlinkOrangeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::LEDBlinkOrangeResponse, ::card_reader_crt::LEDBlinkOrangeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LEDBlinkOrange_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::LEDBlinkOrangeResponse>* CardReader::Stub::AsyncLEDBlinkOrangeRaw(::grpc::ClientContext* context, const ::card_reader_crt::LEDBlinkOrangeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLEDBlinkOrangeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::LEDBlinkRed(::grpc::ClientContext* context, const ::card_reader_crt::LEDBlinkRedRequest& request, ::card_reader_crt::LEDBlinkRedResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::LEDBlinkRedRequest, ::card_reader_crt::LEDBlinkRedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LEDBlinkRed_, context, request, response);
}

void CardReader::Stub::async::LEDBlinkRed(::grpc::ClientContext* context, const ::card_reader_crt::LEDBlinkRedRequest* request, ::card_reader_crt::LEDBlinkRedResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::LEDBlinkRedRequest, ::card_reader_crt::LEDBlinkRedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LEDBlinkRed_, context, request, response, std::move(f));
}

void CardReader::Stub::async::LEDBlinkRed(::grpc::ClientContext* context, const ::card_reader_crt::LEDBlinkRedRequest* request, ::card_reader_crt::LEDBlinkRedResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LEDBlinkRed_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::LEDBlinkRedResponse>* CardReader::Stub::PrepareAsyncLEDBlinkRedRaw(::grpc::ClientContext* context, const ::card_reader_crt::LEDBlinkRedRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::LEDBlinkRedResponse, ::card_reader_crt::LEDBlinkRedRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LEDBlinkRed_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::LEDBlinkRedResponse>* CardReader::Stub::AsyncLEDBlinkRedRaw(::grpc::ClientContext* context, const ::card_reader_crt::LEDBlinkRedRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLEDBlinkRedRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::LEDOFF(::grpc::ClientContext* context, const ::card_reader_crt::LEDOFFRequest& request, ::card_reader_crt::LEDOFFResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::LEDOFFRequest, ::card_reader_crt::LEDOFFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_LEDOFF_, context, request, response);
}

void CardReader::Stub::async::LEDOFF(::grpc::ClientContext* context, const ::card_reader_crt::LEDOFFRequest* request, ::card_reader_crt::LEDOFFResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::LEDOFFRequest, ::card_reader_crt::LEDOFFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LEDOFF_, context, request, response, std::move(f));
}

void CardReader::Stub::async::LEDOFF(::grpc::ClientContext* context, const ::card_reader_crt::LEDOFFRequest* request, ::card_reader_crt::LEDOFFResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_LEDOFF_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::LEDOFFResponse>* CardReader::Stub::PrepareAsyncLEDOFFRaw(::grpc::ClientContext* context, const ::card_reader_crt::LEDOFFRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::LEDOFFResponse, ::card_reader_crt::LEDOFFRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_LEDOFF_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::LEDOFFResponse>* CardReader::Stub::AsyncLEDOFFRaw(::grpc::ClientContext* context, const ::card_reader_crt::LEDOFFRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLEDOFFRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::ReadData(::grpc::ClientContext* context, const ::card_reader_crt::ReadDataRequest& request, ::card_reader_crt::ReadDataResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::ReadDataRequest, ::card_reader_crt::ReadDataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReadData_, context, request, response);
}

void CardReader::Stub::async::ReadData(::grpc::ClientContext* context, const ::card_reader_crt::ReadDataRequest* request, ::card_reader_crt::ReadDataResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::ReadDataRequest, ::card_reader_crt::ReadDataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadData_, context, request, response, std::move(f));
}

void CardReader::Stub::async::ReadData(::grpc::ClientContext* context, const ::card_reader_crt::ReadDataRequest* request, ::card_reader_crt::ReadDataResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReadData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::ReadDataResponse>* CardReader::Stub::PrepareAsyncReadDataRaw(::grpc::ClientContext* context, const ::card_reader_crt::ReadDataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::ReadDataResponse, ::card_reader_crt::ReadDataRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReadData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::ReadDataResponse>* CardReader::Stub::AsyncReadDataRaw(::grpc::ClientContext* context, const ::card_reader_crt::ReadDataRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReadDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::WaitInputReadCard(::grpc::ClientContext* context, const ::card_reader_crt::WaitInputReadCardRequest& request, ::card_reader_crt::WaitInputReadCardResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::WaitInputReadCardRequest, ::card_reader_crt::WaitInputReadCardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_WaitInputReadCard_, context, request, response);
}

void CardReader::Stub::async::WaitInputReadCard(::grpc::ClientContext* context, const ::card_reader_crt::WaitInputReadCardRequest* request, ::card_reader_crt::WaitInputReadCardResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::WaitInputReadCardRequest, ::card_reader_crt::WaitInputReadCardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WaitInputReadCard_, context, request, response, std::move(f));
}

void CardReader::Stub::async::WaitInputReadCard(::grpc::ClientContext* context, const ::card_reader_crt::WaitInputReadCardRequest* request, ::card_reader_crt::WaitInputReadCardResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_WaitInputReadCard_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::WaitInputReadCardResponse>* CardReader::Stub::PrepareAsyncWaitInputReadCardRaw(::grpc::ClientContext* context, const ::card_reader_crt::WaitInputReadCardRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::WaitInputReadCardResponse, ::card_reader_crt::WaitInputReadCardRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_WaitInputReadCard_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::WaitInputReadCardResponse>* CardReader::Stub::AsyncWaitInputReadCardRaw(::grpc::ClientContext* context, const ::card_reader_crt::WaitInputReadCardRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncWaitInputReadCardRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::RejectCardOrMoveBin(::grpc::ClientContext* context, const ::card_reader_crt::RejectCardOrMoveBinRequest& request, ::card_reader_crt::RejectCardOrMoveBinResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::RejectCardOrMoveBinRequest, ::card_reader_crt::RejectCardOrMoveBinResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RejectCardOrMoveBin_, context, request, response);
}

void CardReader::Stub::async::RejectCardOrMoveBin(::grpc::ClientContext* context, const ::card_reader_crt::RejectCardOrMoveBinRequest* request, ::card_reader_crt::RejectCardOrMoveBinResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::RejectCardOrMoveBinRequest, ::card_reader_crt::RejectCardOrMoveBinResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RejectCardOrMoveBin_, context, request, response, std::move(f));
}

void CardReader::Stub::async::RejectCardOrMoveBin(::grpc::ClientContext* context, const ::card_reader_crt::RejectCardOrMoveBinRequest* request, ::card_reader_crt::RejectCardOrMoveBinResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RejectCardOrMoveBin_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::RejectCardOrMoveBinResponse>* CardReader::Stub::PrepareAsyncRejectCardOrMoveBinRaw(::grpc::ClientContext* context, const ::card_reader_crt::RejectCardOrMoveBinRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::RejectCardOrMoveBinResponse, ::card_reader_crt::RejectCardOrMoveBinRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RejectCardOrMoveBin_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::RejectCardOrMoveBinResponse>* CardReader::Stub::AsyncRejectCardOrMoveBinRaw(::grpc::ClientContext* context, const ::card_reader_crt::RejectCardOrMoveBinRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRejectCardOrMoveBinRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status CardReader::Stub::GetDataKartu(::grpc::ClientContext* context, const ::card_reader_crt::GetDataKartuRequest& request, ::card_reader_crt::GetDataKartuResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::card_reader_crt::GetDataKartuRequest, ::card_reader_crt::GetDataKartuResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDataKartu_, context, request, response);
}

void CardReader::Stub::async::GetDataKartu(::grpc::ClientContext* context, const ::card_reader_crt::GetDataKartuRequest* request, ::card_reader_crt::GetDataKartuResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::card_reader_crt::GetDataKartuRequest, ::card_reader_crt::GetDataKartuResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDataKartu_, context, request, response, std::move(f));
}

void CardReader::Stub::async::GetDataKartu(::grpc::ClientContext* context, const ::card_reader_crt::GetDataKartuRequest* request, ::card_reader_crt::GetDataKartuResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDataKartu_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::GetDataKartuResponse>* CardReader::Stub::PrepareAsyncGetDataKartuRaw(::grpc::ClientContext* context, const ::card_reader_crt::GetDataKartuRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::card_reader_crt::GetDataKartuResponse, ::card_reader_crt::GetDataKartuRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDataKartu_, context, request);
}

::grpc::ClientAsyncResponseReader< ::card_reader_crt::GetDataKartuResponse>* CardReader::Stub::AsyncGetDataKartuRaw(::grpc::ClientContext* context, const ::card_reader_crt::GetDataKartuRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDataKartuRaw(context, request, cq);
  result->StartCall();
  return result;
}

CardReader::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::IsOpenRequest, ::card_reader_crt::IsOpenResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::IsOpenRequest* req,
             ::card_reader_crt::IsOpenResp* resp) {
               return service->IsOpen(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::OpenRequest, ::card_reader_crt::OpenResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::OpenRequest* req,
             ::card_reader_crt::OpenResp* resp) {
               return service->Open(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::CloseRequest, ::card_reader_crt::CloseResp, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::CloseRequest* req,
             ::card_reader_crt::CloseResp* resp) {
               return service->Close(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::InitRequest, ::card_reader_crt::InitResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::InitRequest* req,
             ::card_reader_crt::InitResponse* resp) {
               return service->Init(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::PermitMagCardOnlyRequest, ::card_reader_crt::PermitMagCardOnlyResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::PermitMagCardOnlyRequest* req,
             ::card_reader_crt::PermitMagCardOnlyResponse* resp) {
               return service->PermitMagCardOnly(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::ProhibitCardInRequest, ::card_reader_crt::ProhibitCardInResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::ProhibitCardInRequest* req,
             ::card_reader_crt::ProhibitCardInResponse* resp) {
               return service->ProhibitCardIn(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::EjectRequest, ::card_reader_crt::EjectResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::EjectRequest* req,
             ::card_reader_crt::EjectResponse* resp) {
               return service->Eject(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::CaptureRequest, ::card_reader_crt::CaptureResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::CaptureRequest* req,
             ::card_reader_crt::CaptureResponse* resp) {
               return service->Capture(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::RetrieveRequest, ::card_reader_crt::RetrieveResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::RetrieveRequest* req,
             ::card_reader_crt::RetrieveResponse* resp) {
               return service->Retrieve(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::CardStatusRequest, ::card_reader_crt::CardStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::CardStatusRequest* req,
             ::card_reader_crt::CardStatusResponse* resp) {
               return service->CardStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::LEDBlinkGreenRequest, ::card_reader_crt::LEDBlinkGreenResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::LEDBlinkGreenRequest* req,
             ::card_reader_crt::LEDBlinkGreenResponse* resp) {
               return service->LEDBlinkGreen(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::LEDBlinkOrangeRequest, ::card_reader_crt::LEDBlinkOrangeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::LEDBlinkOrangeRequest* req,
             ::card_reader_crt::LEDBlinkOrangeResponse* resp) {
               return service->LEDBlinkOrange(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::LEDBlinkRedRequest, ::card_reader_crt::LEDBlinkRedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::LEDBlinkRedRequest* req,
             ::card_reader_crt::LEDBlinkRedResponse* resp) {
               return service->LEDBlinkRed(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::LEDOFFRequest, ::card_reader_crt::LEDOFFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::LEDOFFRequest* req,
             ::card_reader_crt::LEDOFFResponse* resp) {
               return service->LEDOFF(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::ReadDataRequest, ::card_reader_crt::ReadDataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::ReadDataRequest* req,
             ::card_reader_crt::ReadDataResponse* resp) {
               return service->ReadData(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::WaitInputReadCardRequest, ::card_reader_crt::WaitInputReadCardResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::WaitInputReadCardRequest* req,
             ::card_reader_crt::WaitInputReadCardResponse* resp) {
               return service->WaitInputReadCard(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::RejectCardOrMoveBinRequest, ::card_reader_crt::RejectCardOrMoveBinResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::RejectCardOrMoveBinRequest* req,
             ::card_reader_crt::RejectCardOrMoveBinResponse* resp) {
               return service->RejectCardOrMoveBin(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CardReader_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CardReader::Service, ::card_reader_crt::GetDataKartuRequest, ::card_reader_crt::GetDataKartuResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CardReader::Service* service,
             ::grpc::ServerContext* ctx,
             const ::card_reader_crt::GetDataKartuRequest* req,
             ::card_reader_crt::GetDataKartuResponse* resp) {
               return service->GetDataKartu(ctx, req, resp);
             }, this)));
}

CardReader::Service::~Service() {
}

::grpc::Status CardReader::Service::IsOpen(::grpc::ServerContext* context, const ::card_reader_crt::IsOpenRequest* request, ::card_reader_crt::IsOpenResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::Open(::grpc::ServerContext* context, const ::card_reader_crt::OpenRequest* request, ::card_reader_crt::OpenResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::Close(::grpc::ServerContext* context, const ::card_reader_crt::CloseRequest* request, ::card_reader_crt::CloseResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::Init(::grpc::ServerContext* context, const ::card_reader_crt::InitRequest* request, ::card_reader_crt::InitResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::PermitMagCardOnly(::grpc::ServerContext* context, const ::card_reader_crt::PermitMagCardOnlyRequest* request, ::card_reader_crt::PermitMagCardOnlyResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::ProhibitCardIn(::grpc::ServerContext* context, const ::card_reader_crt::ProhibitCardInRequest* request, ::card_reader_crt::ProhibitCardInResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::Eject(::grpc::ServerContext* context, const ::card_reader_crt::EjectRequest* request, ::card_reader_crt::EjectResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::Capture(::grpc::ServerContext* context, const ::card_reader_crt::CaptureRequest* request, ::card_reader_crt::CaptureResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::Retrieve(::grpc::ServerContext* context, const ::card_reader_crt::RetrieveRequest* request, ::card_reader_crt::RetrieveResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::CardStatus(::grpc::ServerContext* context, const ::card_reader_crt::CardStatusRequest* request, ::card_reader_crt::CardStatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::LEDBlinkGreen(::grpc::ServerContext* context, const ::card_reader_crt::LEDBlinkGreenRequest* request, ::card_reader_crt::LEDBlinkGreenResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::LEDBlinkOrange(::grpc::ServerContext* context, const ::card_reader_crt::LEDBlinkOrangeRequest* request, ::card_reader_crt::LEDBlinkOrangeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::LEDBlinkRed(::grpc::ServerContext* context, const ::card_reader_crt::LEDBlinkRedRequest* request, ::card_reader_crt::LEDBlinkRedResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::LEDOFF(::grpc::ServerContext* context, const ::card_reader_crt::LEDOFFRequest* request, ::card_reader_crt::LEDOFFResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::ReadData(::grpc::ServerContext* context, const ::card_reader_crt::ReadDataRequest* request, ::card_reader_crt::ReadDataResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::WaitInputReadCard(::grpc::ServerContext* context, const ::card_reader_crt::WaitInputReadCardRequest* request, ::card_reader_crt::WaitInputReadCardResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::RejectCardOrMoveBin(::grpc::ServerContext* context, const ::card_reader_crt::RejectCardOrMoveBinRequest* request, ::card_reader_crt::RejectCardOrMoveBinResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status CardReader::Service::GetDataKartu(::grpc::ServerContext* context, const ::card_reader_crt::GetDataKartuRequest* request, ::card_reader_crt::GetDataKartuResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace card_reader_crt

